# Generated by Django 4.1.1 on 2022-09-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrupacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Agrupacion',
                'verbose_name_plural': 'Agrupaciones',
                'db_table': 'agrupacion',
                'ordering': ['agrupacion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Detalleagrupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'detalleagrupacion',
            },
        ),
        migrations.CreateModel(
            name='Detallecategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'detallecategoria',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
    ]
