# Generated by Django 4.1.1 on 2022-09-21 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('datos_persona', models.CharField(max_length=200)),
                ('rrss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.redessociales')),
            ],
            options={
                'db_table': 'origen',
            },
        ),
    ]
