# Generated by Django 4.1.1 on 2022-09-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_estado_estadocivil_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listacalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'listacalles',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'motivo',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nacionalidad',
            },
        ),
    ]
