# Generated by Django 4.1.1 on 2022-09-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0003_listacalles_motivo_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redessociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_social', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'redessociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitante', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'tiposolicitante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadvecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_vecinal', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unidadvecinal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'prioridad',
            },
        ),
    ]
