# Generated by Django 4.1.1 on 2022-09-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0006_incidente_imagenincidentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_cierre_estimado', models.DateField()),
                ('respuesta', models.CharField(max_length=300)),
                ('motivo_negativa', models.CharField(max_length=200)),
                ('id_incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.incidente')),
                ('id_motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.motivo')),
                ('id_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.origen')),
                ('id_prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.prioridad')),
                ('id_tiposolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.tiposolicitante')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'db_table': 'requerimientos',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('casa_dpto', models.CharField(max_length=6)),
                ('id_agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.agrupacion')),
                ('id_calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.listacalles')),
                ('id_detalle_agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.detalleagrupacion')),
                ('id_unidad_vecinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.unidadvecinal')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.usuario')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilio',
            },
        ),
        migrations.CreateModel(
            name='Cambiosestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_cambioestado', models.DateTimeField()),
                ('dato_cambiado', models.CharField(help_text='Dato que se modificó', max_length=500)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.estado')),
                ('id_requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.requerimientos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.usuario')),
            ],
            options={
                'verbose_name': 'Cambio de estado',
                'verbose_name_plural': 'Cambios de estado',
                'db_table': 'cambiosestado',
            },
        ),
    ]
