# Generated by Django 4.1.1 on 2022-09-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0008_prioridad_cantidad_de_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrupacion',
            options={'ordering': ['id'], 'verbose_name': 'Agrupacion', 'verbose_name_plural': 'Agrupaciones'},
        ),
        migrations.AlterModelOptions(
            name='detalleagrupacion',
            options={'verbose_name': 'Detalle Agrupacion  (Nombre)', 'verbose_name_plural': 'Detalle Agrupaciones (Nombre)'},
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='id_agrupacion',
        ),
        migrations.AddField(
            model_name='detalleagrupacion',
            name='id_agrupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requerimientos.agrupacion'),
        ),
    ]
