# Generated by Django 4.1.1 on 2022-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0009_alter_agrupacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['departamento'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='detalleagrupacion',
            options={'ordering': ['id'], 'verbose_name': 'Detalle Agrupacion  (Nombre)', 'verbose_name_plural': 'Detalle Agrupaciones (Nombre)'},
        ),
        migrations.AlterModelOptions(
            name='detallecategoria',
            options={'ordering': ['detalle'], 'verbose_name': 'Detalle Categoria (Nombre)', 'verbose_name_plural': 'Detalle Categorias (Nombre)'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['direccion'], 'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['estado'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'ordering': ['estado_civil'], 'verbose_name': 'Estado Civil', 'verbose_name_plural': 'Estados Civiles'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['genero'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='motivo',
            options={'ordering': ['motivo'], 'verbose_name': 'Motivo', 'verbose_name_plural': 'Motivos'},
        ),
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'ordering': ['nacionalidad'], 'verbose_name': 'Nacionalidad', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelOptions(
            name='origen',
            options={'ordering': ['tipo'], 'verbose_name': 'Origen', 'verbose_name_plural': 'Origenes'},
        ),
        migrations.AlterModelOptions(
            name='prioridad',
            options={'ordering': ['prioridad'], 'verbose_name': 'Prioridad', 'verbose_name_plural': 'Prioridades'},
        ),
        migrations.AlterModelOptions(
            name='redessociales',
            options={'ordering': ['red_social'], 'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'ordering': ['telefono1'], 'verbose_name': 'Telefono', 'verbose_name_plural': 'Telefonos'},
        ),
        migrations.AlterModelOptions(
            name='tiposolicitante',
            options={'ordering': ['tipo_solicitante'], 'verbose_name': 'Tipo de Solicitante', 'verbose_name_plural': 'Tipos de Solicitantes'},
        ),
        migrations.AlterModelOptions(
            name='unidadvecinal',
            options={'ordering': ['unidad_vecinal'], 'verbose_name': 'Unidad Vecinal', 'verbose_name_plural': 'Unidades Vecinales'},
        ),
        migrations.AlterField(
            model_name='agrupacion',
            name='agrupacion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='detalleagrupacion',
            name='detalle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='detallecategoria',
            name='detalle',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='estado_civil',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='listacalles',
            name='calle',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='motivo',
            name='motivo',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nacionalidad',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='origen',
            name='tipo',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='prioridad',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='redessociales',
            name='red_social',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposolicitante',
            name='tipo_solicitante',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadvecinal',
            name='unidad_vecinal',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(unique=True),
        ),
    ]
