# Generated by Django 4.1.1 on 2022-09-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0010_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'ordering': ['id'], 'verbose_name': 'Estado Civil', 'verbose_name_plural': 'Estados Civiles'},
        ),
        migrations.AlterModelOptions(
            name='listacalles',
            options={'ordering': ['calle']},
        ),
        migrations.AlterModelOptions(
            name='unidadvecinal',
            options={'ordering': ['id'], 'verbose_name': 'Unidad Vecinal', 'verbose_name_plural': 'Unidades Vecinales'},
        ),
        migrations.AlterField(
            model_name='detalleagrupacion',
            name='detalle',
            field=models.CharField(help_text='Nombre de la Agrupacion habitacional', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(help_text='Genero de la persona', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='imagenincidentes',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_mat',
            field=models.CharField(help_text='Ingrese su apellido materno', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_pat',
            field=models.CharField(help_text='Ingrese su apellido paterno', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Ingrese su fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(help_text='Ingrese su primer nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(help_text='Ingrese su segundo nombre', max_length=100),
        ),
    ]
