# Generated by Django 4.1.1 on 2022-09-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0011_alter_estadocivil_options_alter_listacalles_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenincidentes',
            name='imagen',
        ),
    ]
