# Generated by Django 4.1.1 on 2022-09-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0012_remove_imagenincidentes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenincidentes',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
