# Generated by Django 4.1.1 on 2022-09-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0013_imagenincidentes_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenincidentes',
            options={'verbose_name': 'Imagen Incidente', 'verbose_name_plural': 'Imagenes Incidentes'},
        ),
        migrations.RemoveField(
            model_name='imagenincidentes',
            name='imagen',
        ),
    ]
