# Generated by Django 4.1.1 on 2022-09-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0014_alter_imagenincidentes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenincidentes',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
