# Generated by Django 4.1.1 on 2022-09-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0016_alter_usuario_digito_verif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidente',
            options={'verbose_name': 'Incidente', 'verbose_name_plural': 'Incidentes'},
        ),
    ]
